Demko Gleb contest 4 task A
demagleb/2-3_tree pull request #1
Opened 2022-02-25 16:06 UTC by demagleb

2022-03-20 20:54 UTC, Gleb-Tretyakov requested changes

2022-03-20 20:54 UTC, Gleb-Tretyakov commented on tree.h
> +#include <vector>
отсортить инклюды

2022-03-20 20:54 UTC, Gleb-Tretyakov commented on tree.h
> +    Node_ *sons[4];
числа в константы.
C'шные массивы это вообще плохо, сделай хотя бы array

2022-03-20 20:54 UTC, Gleb-Tretyakov commented on tree.h
> +    int sons_size = 0;
int не делаем смотри codestyle, для size'ов size_t

2022-03-20 20:54 UTC, Gleb-Tretyakov commented on tree.h
> +class Set;
А зачем?

2022-03-20 20:54 UTC, Gleb-Tretyakov commented on tree.h
> +class Iterator : public std::iterator<std::bidirectional_iterator_tag, T> {
Сделай iterator и node в Set, зачем торчать наружу

2022-03-20 20:54 UTC, Gleb-Tretyakov commented on tree.h
> +    friend Set<T>;
friend не делаем

2022-03-20 20:54 UTC, Gleb-Tretyakov commented on tree.h
> +    void check_version_() const;
нейминг странный

2022-03-20 20:54 UTC, Gleb-Tretyakov commented on tree.h
> +struct Node_ {
_ не нужен

2022-03-20 20:54 UTC, Gleb-Tretyakov commented on tree.h
> +    Iterator<T> operator++(int);
опять же int'ов не делаем

2022-03-20 20:54 UTC, Gleb-Tretyakov commented on tree.h
> +    Iterator<T> operator--(int);
А без <T> не работает?

2022-03-20 20:54 UTC, Gleb-Tretyakov commented on tree.h
> +    bool operator==(const Iterator &iter) const;
& к типу

2022-03-20 20:54 UTC, Gleb-Tretyakov commented on tree.h
> +    for (auto i = first; i != last; ++i) {
Ну тут лучше auto заменить на тип, ты потом *i делаешь, непонятно что и куда идет передается

2022-03-20 20:54 UTC, Gleb-Tretyakov commented on tree.h
> +bool Set<T>::empty() const {
Обычно короткие функции inline и внутри класса

2022-03-20 20:54 UTC, Gleb-Tretyakov commented on tree.h
> +    auto son = cur_;
auto везде убираем, если это не ranged base for

2022-03-20 20:54 UTC, Gleb-Tretyakov commented on tree.h
> +
Не хватает комментариев

2022-03-24 15:24 UTC, demagleb commented on tree.h
> +
Добавил

2022-03-29 13:26 UTC, demkog commented on tree.h
> +
Последняя посылка: 66326449. Отличается от текущей версии только комментариями.

2022-03-30 16:24 UTC, Gleb-Tretyakov commented
Порезолвь issue и пришли ссылкой посылку

2022-03-30 16:28 UTC, Gleb-Tretyakov commented on tree.h
> +    static const size_t MAX_SONS = 4;
constexpr

2022-03-30 16:28 UTC, Gleb-Tretyakov commented on tree.h
> +    if (*node->val < elem || elem < *node->val) return;
всегда с {}
поправиь везде

2022-03-30 16:28 UTC, Gleb-Tretyakov commented on tree.h
> +    son = *(
плохой перенос

2022-03-30 16:28 UTC, Gleb-Tretyakov commented on tree.h
> +    for (size_t i = node->sons_size - 2; i < MAX_SONS; --i) {
вот тут плохо, вдруг sons_size < 2

2022-03-30 17:01 UTC, demagleb commented on tree.h
> +    for (size_t i = node->sons_size - 2; i < MAX_SONS; --i) {
Тогда цикл ведь сразу завершится

2022-03-30 17:09 UTC, demkog commented on tree.h
> +    for (size_t i = node->sons_size - 2; i < MAX_SONS; --i) {
тогда ведь цикл сразу завершится

2022-10-19 09:52 UTC, merged